[package]
name = "pallet-communities"
version = "0.1.0"
description = "This pallet enables the creation of communities that are soverign entities with diverse forms of governance. In simpler terms, it can be considered a DAO Factory."
authors = ["Virto Team<contact@virto.team>"]
edition = "2021"
license = "MIT-0"
publish = false
repository = "https://github.com/virto-network/virto-node/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }

frame-benchmarking = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks", optional = true }
frame-support =  { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }
frame-system = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }
sp-runtime = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }
sp-std = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }

pallet-referenda = { default-features = false, git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks", optional = true }

[dev-dependencies]
sp-core = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }
sp-io = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }

pallet-assets = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }
pallet-balances = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }
pallet-preimage = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }
pallet-scheduler = { git = "https://github.com/olanod/polkadot-sdk.git", branch = "olanod-referenda-owned-tracks" }

[features]
default = ["std", "referenda"]
referenda = ["dep:pallet-referenda"]
std = [
	"parity-scale-codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-referenda?/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
