[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node/parachain',
    'node/standalone',
    'pallets/backed_asset',
    'pallets/foreign_asset',
    'pallets/human_swap',
    'pallets/transfers',
    'pallets/rate_provider',
    'primitives',
    'runtime'
]

