[profile.release]
panic = 'unwind'

[workspace]
members = [
    'commons',
    'node',
    'runtime',
    'pallets/foreign_asset',
    'pallets/backed_asset',
    'pallets/human_swap',
    'pallets/transfers',
]
