[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/backed_asset',
    'pallets/foreign_asset',
    'pallets/human_swap',
    'pallets/transfers',
    'primitives',
    'runtime',
]
