[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.0' }
serde = { default-features = false, features = ['derive'], optional = true, version = '1.0' }

[features]
default = []
std = [
    'parity-scale-codec/std',
    'serde'
]

[package]
authors = ['The Valiu team']
description = 'Valiu node commons'
edition = '2018'
homepage = 'https://github.com/valibre-org/node'
license = 'Unlicense'
name = 'valiu-node-commons'
readme = 'README.md'
repository = 'https://github.com/valibre-org/node'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
