[package]
authors = ['Daniel Olano <daniel@olanod.com>']
edition = '2018'
homepage = 'https://github.com/valibre-org/node'
license = 'Unlicense'
name = 'vln-runtime'
repository = 'https://github.com/valibre-org/node'
version = '2.0.0'
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies.wasm-builder-runner]
package = "substrate-wasm-builder-runner"
version = "1.0.6"
[dependencies.codec]
default-features = false
features = ['derive']
package = "parity-scale-codec"
version = "1.3.5"

[dependencies.frame-benchmarking]
default-features = false
optional = true
version = "2.0.0"

[dependencies.frame-executive]
default-features = false
version = "2.0.0"

[dependencies.frame-support]
default-features = false
version = "2.0.0"

[dependencies.frame-system]
default-features = false
version = "2.0.0"

[dependencies.frame-system-benchmarking]
default-features = false
optional = true
version = "2.0.0"

[dependencies.frame-system-rpc-runtime-api]
default-features = false
version = "2.0.0"

[dependencies.hex-literal]
optional = true
version = "0.3.1"

[dependencies.pallet-membership]
default-features = false
version = "2.0.0"

[dependencies.pallet-aura]
default-features = false
version = "2.0.0"

[dependencies.pallet-balances]
default-features = false
version = "2.0.0"

[dependencies.pallet-grandpa]
default-features = false
version = "2.0.0"

[dependencies.pallet-randomness-collective-flip]
default-features = false
version = "2.0.0"

[dependencies.pallet-sudo]
default-features = false
version = "2.0.0"

[dependencies.pallet-timestamp]
default-features = false
version = "2.0.0"

[dependencies.pallet-transaction-payment]
default-features = false
version = "2.0.0"

[dependencies.pallet-transaction-payment-rpc-runtime-api]
default-features = false
version = "2.0.0"

[dependencies.serde]
features = ['derive']
optional = true
version = "1.0.116"

[dependencies.sp-api]
default-features = false
version = "2.0.0"

[dependencies.sp-block-builder]
default-features = false
version = "2.0.0"

[dependencies.sp-consensus-aura]
default-features = false
version = "0.8.0"

[dependencies.sp-core]
default-features = false
version = "2.0.0"

[dependencies.sp-inherents]
default-features = false
version = "2.0.0"

[dependencies.sp-offchain]
default-features = false
version = "2.0.0"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0"

[dependencies.sp-session]
default-features = false
version = "2.0.0"

[dependencies.sp-std]
default-features = false
version = "2.0.0"

[dependencies.sp-transaction-pool]
default-features = false
version = "2.0.0"

[dependencies.sp-version]
default-features = false
version = "2.0.0"

[dependencies.pallet-provider]
default-features = false
package = 'pallet-provider'
path = '../pallets/liquidity-provider'
version = '0.1.0'

[dependencies.orml-tokens]
default-features = false
version = "0.3"

[dependencies.pallet-usdv-minting]
default-features = false
path = '../pallets/usdv-minting'
version = '0.1.0'

[dependencies.valiu-node-commons]
default-features = false
path = '../valiu-node-commons'

[features]
default = ['std']
runtime-benchmarks = [
    'sp-runtime/runtime-benchmarks',
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'hex-literal',
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
]
std = [
    'codec/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system-rpc-runtime-api/std',
    'frame-system/std',
    'orml-tokens/std',
    'pallet-aura/std',
    'pallet-balances/std',
    'pallet-grandpa/std',
    'pallet-membership/std',
    'pallet-provider/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-transaction-payment/std',
    'pallet-usdv-minting/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
]
