[package]
authors = ['Daniel Olano <daniel@olanod.com>']
edition = '2018'
homepage = 'https://github.com/valibre-org/node'
license = 'Unlicense'
name = 'vln-parachain-runtime'
repository = 'https://github.com/valibre-org/node'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { default-features = false, version = "4.0.0" }

[dependencies]
# Substrate dependencies - https://github.com/substrate-developer-hub/substrate-parachain-template/blob/master/runtime/Cargo.toml
hex-literal = {version = "0.3.1", optional = true}
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "rococo-v1" }
frame-system-benchmarking = {git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "rococo-v1"}
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
serde = { default-features = false, features = ['derive'], optional = true, version = "1.0.119" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }

# Cumulus dependencies
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "rococo-v1"}
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "rococo-v1"}
cumulus-pallet-xcm-handler = {git = "https://github.com/paritytech/cumulus", default-features = false, branch = "rococo-v1"}
parachain-info = {git = "https://github.com/paritytech/cumulus", default-features = false, branch = "rococo-v1"}

# polkadot dependencies
xcm = {git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rococo-v1"}
xcm-builder = {git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rococo-v1"}
xcm-executor = {git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rococo-v1"}
polkadot-parachain = {git = "https://github.com/paritytech/polkadot", default-features = false, branch = "rococo-v1"}

# Vln dependencies
# orml-tokens = { default-features = false, version = "0.4.0" }
# orml-traits = { default-features = false, version = "0.4.0" }
# orml-oracle = { default-features = false, version = "0.4.0" }
# pallet-membership = { default-features = false, version = "3.0.0" }
# pallet-proxy = { default-features = false, version = "3.0.0" }

# Local dependencies
vln-primitives = { default-features = false, path = '../../primitives' }
# vln-foreign-asset = { default-features = false, path = '../../pallets/foreign_asset' }
# vln-backed-asset = { default-features = false, path = '../../pallets/backed_asset' }
# vln-human-swap = { default-features = false, path = '../../pallets/human_swap' }
# vln-transfers = { default-features = false, path = '../../pallets/transfers' }

[features]
default = ['std']

runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'frame-system/runtime-benchmarks',
    'hex-literal',
    'pallet-timestamp/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]
std = [
    'frame-executive/std',
    'frame-support/std',
    'frame-system-rpc-runtime-api/std',
    'frame-system/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'parity-scale-codec/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    "parachain-info/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-primitives-core/std",
    "xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"cumulus-pallet-xcm-handler/std",
    'vln-primitives/std',
    # 'vln-foreign-asset/std',
    # 'vln-backed-asset/std',
    # 'vln-human-swap/std',
    # 'vln-transfers/std',
    # 'orml-tokens/std',
    # 'orml-oracle/std',
    # 'pallet-proxy/std',
]
