[package]
name = "pallet-payments"
version = "0.1.0"
authors = ['Virto Team <contact@virto.team>']
license = "GPL-3.0-only"
homepage = 'https://github.com/virto-network/virto-node'
repository = 'https://github.com/virto-network/virto-node'
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = [ "derive" ] }
scale-info = { workspace = true }
sp-runtime = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
sp-std = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
sp-core = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
sp-io = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
frame-benchmarking = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
frame-support = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
frame-system = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }


[dev-dependencies]
serde = { version = "1.0.132" }
pallet-balances = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
pallet-sudo = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
pallet-assets = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }
sp-keystore = { git = "https://github.com/virto-network/polkadot-sdk", default-features = false, branch = "feat-add-hold-traits-pallet-asset" }



[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"pallet-balances/std",
	"pallet-sudo/std",
	"pallet-assets/std",
	"sp-std/std"
]
try-runtime = [ "frame-support/try-runtime" ]
