[package]
name = "pallet-payments"
version = "0.1.0"
authors = ['Virto Team <contact@virto.team>']
license = "GPL-3.0-only"
homepage = 'https://github.com/virto-network/virto-node'
repository = 'https://github.com/virto-network/virto-node'
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"], default-features = false }
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }
log = "0.4.0"

# Substrate
frame-benchmarking = { git = "https://github.com/virto-network/substrate", default-features = false, optional = true, branch = "nicof-adding-hold-traits-asset-pallet" }
frame-support = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
frame-system = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
sp-runtime = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
sp-std = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
sp-io = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }

[dev-dependencies]
serde = { version = "1.0.132" }
pallet-balances = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
pallet-sudo = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
pallet-assets = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
sp-keystore = { git = "https://github.com/virto-network/substrate", branch = "nicof-adding-hold-traits-asset-pallet" }

# Substrate
sp-core = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
sp-io = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }
sp-runtime = { git = "https://github.com/virto-network/substrate", default-features = false, branch = "nicof-adding-hold-traits-asset-pallet" }

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"pallet-balances/std",
	"pallet-sudo/std",
	"pallet-assets/std",
	"sp-std/std",
	"sp-io/std",
]
try-runtime = [ "frame-support/try-runtime" ]
