[dependencies]
frame-support = { default-features = false, version = '2.0' }
frame-system = { default-features = false, version = '2.0' }
orml-traits = { default-features = false, version = '0.3' }
pallet-membership = { default-features = false, version = '2.0' }
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.0' }
sp-std = { default-features = false, version = '2.0' }
valiu-node-commons = { default-features = false, path = '../../valiu-node-commons' }

[dev-dependencies]
orml-tokens = { default-features = false, version = '0.3' }
sp-core = { default-features = false, version = '2.0' }
sp-io = { default-features = false, version = '2.0' }
sp-runtime = { default-features = false, version = '2.0' }

[features]
default = ['std']
std = [
    'frame-support/std',
    'frame-system/std',
    'orml-traits/std',
    'pallet-membership/std',
    'parity-scale-codec/std',
    'sp-std/std',
    'valiu-node-commons/std',
]

[package]
authors = ['The Valiu team']
description = 'USDv minting'
edition = '2018'
homepage = 'https://github.com/valibre-org/node'
license = 'Unlicense'
name = 'pallet-usdv-minting'
readme = 'README.md'
repository = 'https://github.com/valibre-org/node'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
