[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "./bin/polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 10000
  extra_args = [ "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all" ]

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all" ]

  [[relaychain.nodes]]
  name = "dave"
  validator = true
  extra_args = [ "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all" ]

[[parachains]]
id = 2281
add_to_genesis = true
cumulus_based = true
chain = "kreivo-rococo-local"

  [[parachains.collators]]
  name = "kreivo1"
  command = "./target/release/virto-node"
  ws_port = 20000
  args = ["--force-authoring --log=xcm=trace"]

  [[parachains.collators]]
  name = "kreivo2"
  command = "./target/release/virto-node"
  ws_port = 21000
  args = ["--force-authoring --log=xcm=trace"]