[settings]
timeout = 1000

[relaychain]
chain = "kusama-local"
chain_spec_command = "./bin/runtimes/polkadot/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
default_args = ["-lparachain=debug", "-lxcm=trace"]
default_command = "./bin/polkadot"

[[relaychain.nodes]]
extra_args = ["--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all"]
name = "alice"
validator = true
ws_port = 10000

[[relaychain.nodes]]
extra_args = ["--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all"]
name = "bob"
validator = true

[[relaychain.nodes]]
extra_args = ["--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all"]
name = "charlie"
validator = true

[[relaychain.nodes]]
extra_args = ["--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all"]
name = "dave"
validator = true

[[parachains]]
add_to_genesis = true
chain = "local"
cumulus_based = true
id = 2281
onboard_as_parachain = true

[[parachains.collators]]
args = ["--force-authoring --log=xcm=trace,parachain=trace"]
command = "./target/release/virto-node"
name = "kreivo1"
ws_port = 20000

[[parachains.collators]]
args = ["--force-authoring --log=xcm=trace,parachain=trace"]
command = "./target/release/virto-node"
name = "kreivo2"
ws_port = 21000
