[package]
authors = ['Daniel Olano <daniel@olanod.com>']
build = 'build.rs'
description = 'Valiu Liquidity Network - Node'
edition = '2018'
homepage = 'https://github.com/valibre-org/node'
license = 'Unlicense'
name = 'vln-node'
repository = 'https://github.com/valibre-org/node'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
frame-benchmarking = { optional = true, version = "3.0.0" }
frame-benchmarking-cli = { optional = true, version = "3.0.0" }
jsonrpc-core = "15.1.0"
sc-basic-authorship = "0.9.0"
sc-cli = { version = "0.9.0", features = ['wasmtime'] }
sc-client-api = "3.0.0"
sc-consensus = "0.9.0"
sc-consensus-aura = "0.9.0"
sc-executor = { version = "0.9.0", features = ['wasmtime'] }
sc-finality-grandpa = "0.9.0"
sc-keystore = "3.0.0"
sc-rpc = "3.0.0"
sc-rpc-api = "0.9.0"
sc-service = { version = "0.9.0", features = ['wasmtime'] }
sc-transaction-pool = "3.0.0"
serde_json = "1.0.62"
sp-api = "3.0.0"
sp-block-builder = "3.0.0"
sp-blockchain = "3.0.0"
sp-consensus = "0.9.0"
sp-consensus-aura = "0.9.0"
sp-core = "3.0.0"
sp-finality-grandpa = "3.0.0"
sp-inherents = "3.0.0"
sp-runtime = "3.0.0"
sp-transaction-pool = "3.0.0"
structopt = "0.3.21"
substrate-frame-rpc-system = "3.0.0"
vln-runtime = { path = '../runtime', version = '2.0.0' }

[build-dependencies]
substrate-build-script-utils = "3.0.0"

[features]
default = []
native-runtime-benchmarks = ['runtime-benchmarks', 'vln-runtime/native-runtime-benchmarks']
runtime-benchmarks = [
    'frame-benchmarking-cli',
    'frame-benchmarking',
    'vln-runtime/runtime-benchmarks'
]

[[bin]]
name = 'vln_node'
path = 'src/main.rs'
