[package]
authors = ['Daniel Olano <daniel@olanod.com>']
build = 'build.rs'
description = 'Valiu Liquidity Network - Node'
edition = '2018'
homepage = 'https://github.com/valibre-org/node'
license = 'Unlicense'
name = 'vln-node'
repository = 'https://github.com/valibre-org/node'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
frame-benchmarking = { optional = true, version = '2.0.0' }
frame-benchmarking-cli = { optional = true, version = '2.0.0' }
jsonrpc-core = '15.0.0'
pallet-membership = '2.0'
sc-basic-authorship = '0.8.0'
sc-cli = { version = '0.8.0', features = ['wasmtime'] }
sc-client-api = '2.0.0'
sc-consensus = '0.8.0'
sc-consensus-aura = '0.8.0'
sc-executor = { version = '0.8.0', features = ['wasmtime'] }
sc-finality-grandpa = '0.8.0'
sc-rpc = '2.0.0'
sc-rpc-api = '0.8.0'
sc-service = { version = '0.8.0', features = ['wasmtime'] }
sc-transaction-pool = '2.0.0'
serde_json = '1.0'
sp-api = '2.0.0'
sp-block-builder = '2.0.0'
sp-blockchain = '2.0.0'
sp-consensus = '0.8.0'
sp-consensus-aura = '0.8.0'
sp-core = '2.0.0'
sp-finality-grandpa = '2.0.0'
sp-inherents = '2.0.0'
sp-runtime = '2.0.0'
sp-transaction-pool = '2.0.0'
structopt = '0.3.8'
substrate-frame-rpc-system = '2.0.0'
vln-commons = { features = ['std'], path = '../commons' }
vln-runtime = { path = '../runtime', version = '2.0.0' }

[build-dependencies]
substrate-build-script-utils = '2.0.0'

[features]
default = []
native-runtime-benchmarks = ['runtime-benchmarks', 'vln-runtime/native-runtime-benchmarks']
runtime-benchmarks = [
    'frame-benchmarking-cli',
    'frame-benchmarking',
    'vln-runtime/runtime-benchmarks'
]

[[bin]]
name = 'vln_node'
path = 'src/main.rs'
