name: Benchmarks

on:
  push:
    branches: 
      - 'feat/ci-benchmarking'
      - master

jobs:
  build:
    name: Build with Benchmarks
    runs-on: [self-hosted, builder]
    steps:
      - uses: actions/checkout@v4
      - run: just build-local runtime-benchmarks
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_number }}-virto-node
          path: ./target/release/virto-node
      - uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-cache
        
  benchmark:
    name: Build with Benchmarks
    needs: build
    runs-on: [self-hosted, benchmarks]
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p .benchmarking-logs target/release
      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_number }}-virto-node
          path: ./target/release
      - run: |
          just benchmark pallet_payments
      - uses: actions/upload-artifact@v3
        with:
            name: ${{ github.run_id }}-weight-files
            path: ./runtime/kreivo/src/weights
      - uses: actions/upload-artifact@v3
        with:
            name: ${{ github.run_id }}-benchmark_logs
            path: ./.benchmarking-logs
      # TODO: Generate the PR based on the resulting files
