name: Benchmarks

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Target
    runs-on: [self-hosted, builder]
    steps:
      - uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-cache
      - uses: actions/checkout@v4
      - run: just build-local runtime-benchmarks
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_number }}-virto-node
          path: ./target/release/virto-node
        
  benchmark:
    name: Run Benchmarks
    needs: build
    runs-on: [self-hosted, benchmarks]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p .benchmarking-logs target/release
      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_number }}-virto-node
          path: ./target/release
      - run: |
          just benchmarks
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}-benchmark_logs
          path: ./.benchmarking-logs
      - uses: peter-evans/create-pull-request@v6
        with:
          add-paths: runtime/kreivo/src/weights
          commit-message: '[ci] calculate weights'
          branch: benchmarks
          branch-suffix: short-commit-hash
          title: "Benchmarking: Calculate weights for ${{ github.sha }}"
          body: |
            This Pull Request is automatically raised when pushing over `master`
            and should be resolved and reviewed manually.
          assignees: ${{ github.actor_id }}
