name: Benchmarks

on:
  push:
    branches: 
      - 'feat/ci-benchmarking'
      - master

jobs:
  benchmark:
    name: Build with Benchmarks
    runs-on: [self-hosted, benchmarks]
    steps:
      - uses: actions/checkout@v4
      - run: just build-local runtime-benchmarks
      - run: |
          mkdir benchmark_logs
          just benchmark pallet_payments
      - uses: actions/upload-artifact@v3
        with:
            name: ${{ github.run_id }}-weight-files
            path: ./runtime/kreivo/src/weights
      - uses: actions/upload-artifact@v3
        with:
            name: ${{ github.run_id }}-benchmark_logs
            path: ./benchmark_logs
      - run: rm -rf benchmark_logs
      # TODO: Generate the PR based on the resulting files