name: Checks

on:
  pull_request:

jobs:
  build:
    name: Check lint
    runs-on: [self-hosted, builder]
    steps:
      - uses: actions/checkout@v4
      - run: just check
      - uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-cache

  tests:
    name: Check project
    runs-on: [self-hosted, builder]
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: just test
      - uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-cache