name: Checks

on:
  pull_request:

jobs:
  build:
    name: Check lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: make check

  tests:
    name: Unit tests
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: cargo test

  benchmarks:
    name: Unit tests
    runs-on: self-hosted
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --features runtime-benchmarks
