name: Release tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build node
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1 
        with:
          toolchain: nightly-2021-04-22
          target: wasm32-unknown-unknown 

      - name: Build parachain node
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p vln-parachain
      
      - name: Build parachain artifacts
        run: |
          mkdir -p build/
          ./target/release/vln_parachain export-genesis-state --chain testnet > build/genesis-state
          ./target/release/vln_parachain export-genesis-wasm --chain testnet > build/genesis-wasm
          ./target/release/vln_parachain build-spec --chain testnet --disable-default-bootnode > build/testnet-chainspec
          cp target/release/vln_parachain build/vln
      
  release:
    name: Create GH Release
    needs: build
    runs-on: self-hosted
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PATH: build/
          GHR_COMPRESS: gz

  container:
    name: Containerize & Publish
    needs: build
    runs-on: self-hosted
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: valibre/vln
          build-args: |
            VCS_REF=${{ github.ref }}
            IMAGE_NAME=valibre/vln
            BUILD_DATE=${{ steps.date.outputs.date }}
          dockerfiles: |
            ./Containerfile

      - name: Publish image
        uses: redhat-actions/push-to-registry@v2
        id: registry
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: hub.docker.com
          username: ${{ secrets.REGISTRY_USER }}
          rpassword: ${{ secrets.REGISTRY_TOKEN }}

