name: Release tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build node
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build parachain node & artifacts
        run: just build-container-local
      
  release:
    name: Create GH Release
    needs: build
    runs-on: self-hosted
    steps:
      - name: Build collator artifacts
        run: just release-artifacts
      - name: Build full-node artifacts
        run: just rol=full release-artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release/*

  container:
    name: Containerize & Publish
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish image
        run: |
          podman push ghcr.io/virto-network/virto:$(just version)
          podman push ghcr.io/virto-network/virto:latest
