name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build&Release project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1 
        with:
          toolchain: nightly-2021-06-27
          target: wasm32-unknown-unknown 

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p vln-parachain
      
      - name: Build parachain artifacts
        run: |
          ./target/release/vln_parachain export-genesis-state --chain testnet > genesis-state
          ./target/release/vln_parachain export-genesis-wasm --chain testnet > genesis-wasm
          ./target/release/vln_parachain build-spec --chain testnet --disable-default-bootnode > testnet-chainspec
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            target/release/vln_parachain
            genesis-state
            genesis-wasm
            testnet-chainspec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  container:
    name: Containerize
    runs-on: self-hosted
    steps:
      - id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: valibre/vln
          build-args: |
            VCS_REF=${{ github.ref }}
            IMAGE_NAME=valibre/vln
            BUILD_DATE=${{ steps.date.outputs.date }}
          dockerfiles: |
            ./Containerfile

      - name: Publish image
