name: Release tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build node
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build parachain node & artifacts
        run: just build-container ${GITHUB_REF#refs/tags/}
      
  # release:
  #   name: Create GH Release
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         files: |
  #           build/testnet_genesis_state
  #           build/testnet_genesis_wasm
  #           build/testnet_chainspec

  container:
    name: Containerize & Publish
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ghcr.io

      - name: Publish image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: virto-network/virto
          registry: ghcr.io

