name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build node
    runs-on: [self-hosted, builder]
    steps:
      - uses: actions/checkout@v4

      - name: Build parachain node & artifacts
        run: just build-container-local
      
  release:
    name: Create GH Release
    needs: build
    runs-on: [self-hosted, builder]
    steps:
      - name: Build collator artifacts
        run: just release-artifacts
      - name: Build full-node artifacts
        run: just rol=full release-artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release/*
