name: Blockchain Node

on:
  push: 
    branches:
    - master

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo directories
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }} 
      - uses: actions-rs/toolchain@v1 
        with:
          toolchain: nightly-2020-10-01
          target: wasm32-unknown-unknown 
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Package files
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: |
            .codedeploy/**/*
            target/release/vln_node

  package:
    name: Codedeploy Node
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node: 
        - name: test-odin
          args: '--rpc-methods unsafe'
          bucket: deploy-valiu
        - name: test-thor
          bucket: de-deploy-valiu
          args: '--bootnodes test.valibre.network --rpc-methods unsafe'
        - name: test-loki
          bucket: ca-deploy-valiu
          args: '--bootnodes test.valibre.network --rpc-methods unsafe'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - name: Adapt service file
        run: |
          sed -i 's/CHAIN_NAME/${{ matrix.node.name }}/' .codedeploy/app.service
          sed -i 's/EXTRA_ARGS/${{ matrix.node.args }}/' .codedeploy/app.service
      - name: Create app.zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -rj app . -i target/release/vln_node .codedeploy/*
      - name: S3 Upload
        uses: hannut91/aws-cli@1.18.65
        with:
          args: s3 mv app.zip s3://${{ matrix.node.bucket }}/valibre-org/node/ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

