name: Blockchain Node

on:
  push: 
    branches:
    - master

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo directories
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }} 
      - uses: actions-rs/toolchain@v1 
        with:
          toolchain: nightly-2021-02-17
          target: wasm32-unknown-unknown 
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Package files
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: |
            .codedeploy/**/*
            target/release/vln_node

  package:
    name: Codedeploy Node
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - name: Create app.zip
        run: zip -rj app target/release/vln_node .codedeploy/*
      - name: S3 Upload
        uses: hannut91/aws-cli@1.18.65
        with:
          args: s3 mv app.zip s3://${{ secrets.DEPLOY_BUCKET }}/valibre-org/node/ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

