name: Test parachain

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions-rs/toolchain@v1 
        with:
          toolchain: nightly-2021-04-22
          target: wasm32-unknown-unknown 

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p vln-parachain

