name: Test parachain

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Test parachain
        run: make test_parachain
